version: '3.4'

services:
  db:
    image: postgres:12-alpine
    container_name: parcel-delivery-database
    expose:
      - '5432'
    ports:
      - '54321:5432'
    environment:
      - PG_PASSWORD=password
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db-data:/var/lib/postgresql/data/
  authentication-service:
    image: authentication-service
    build:
      context: .
      dockerfile: ./services/authentication-service/Dockerfile.debug
    depends_on:
      - "db"
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - '9229:9229'
    environment:
      PORT: "8080"
      DATABASE_URL: "postgresql://postgres:password@host.docker.internal:54321/postgres"
      USER_AUTH_SECRET: "rJ0x7OzQ*8br"
  parcel-service:
    image: parcel-service
    build:
      context: .
      dockerfile: ./services/parcel-service/Dockerfile.debug
    depends_on:
      - "db"
    environment:
      NODE_ENV: development
    ports:
      - 8081:8081
      - 9230:9230
    environment:
      PORT: "8081"
      DATABASE_URL: "postgresql://postgres:password@host.docker.internal:54321/postgres"
      USER_AUTH_SECRET: "rJ0x7OzQ*8br"