FROM node:16-alpine AS build-stage

ENV INSTALL_PATH /usr/src/app
WORKDIR $INSTALL_PATH

COPY tsconfig.json .
COPY package* .
COPY prisma ./prisma/

RUN mkdir -p $INSTALL_PATH/services/parcel-service
COPY ./services/parcel-service ./services/parcel-service

RUN npm ci

EXPOSE 8081
CMD ["npm", "run", "start", "-w", "services/parcel-service"]