# Build Stage
FROM node:16-alpine AS build-stage

ENV INSTALL_PATH /usr/src/app
WORKDIR $INSTALL_PATH

COPY tsconfig.json .
COPY package* .
COPY prisma ./prisma/

RUN mkdir -p $INSTALL_PATH/services/authentication-service
COPY ./services/authentication-service ./services/authentication-service

RUN npm ci

EXPOSE 8080
CMD ["npm", "run", "start", "-w", "services/authentication-service"]